# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        node-version: '20'

    - uses: Silleellie/pylint-github-action@v2
      with:
        lint-path: client.py
        python-version: 3.9
        color-good-score: brightgreen
        color-perfect-score: brightgreen
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint client.py

    - name: Run tests and collect coverage
      run: |
        coverage run -m unittest test.py client.py & (sleep 3; coverage xml)
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: pete1328/Othello
